package com.bumptech.glide.annotation.compiler;

/**
 * Generates unique field ids for classes generated by Glide's annotation processor.
 */
final class FieldUniqueIdGenerator {
  private static int nextStaticFieldUniqueId;

  private FieldUniqueIdGenerator() {
    // Utility class.
  }

  static int next() {
    return nextStaticFieldUniqueId++;
  }
}
